[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/Atlas/Free/signup.html"
  status = 200

[[redirects]]
  from = "/Paid/*"
  to = "/.netlify/functions/servePaidContentSimple?page=:splat"
  status = 200

[[redirects]]
  from = "/paid/*"
  to = "/.netlify/functions/servePaidContentSimple?page=:splat"
  status = 200
